import AYconverter as c
#Name: Andrew Young
#Class: INFO 1200
#Section: See syllabus, schedule, or Canvas course for section number
#Professor: Barty
#Date:
#Project #: MO5_P1
#By submitting this assignment, I declare that the source code contained in this assignment was written s#olely by me, unless specifically provided in the assignment. I attest that no part of this assignment, i#n whole or in part, was generated by Generative Artificial Intelligence (e.g., ChatGPT, Gemini, Copilot, #Claude, etc.) nor obtained from a paid solution service (e.g., Chegg, Course Hero, Bartleby, etc.). I un#derstand that copying any source code, in whole or in part, constitutes cheating, and that I will receiv#e a zero on this project if I am found in violation of this policy.

print("Andrew Young's Feet/Meters Converter")
print()


def fm_welcome():
    print("Andrew's Feet and Meters Converter")
    print()

def fm_menu():
    print("Conversions Menu")
    print("a. Feet to Meters")
    print("b. Meters to Feet")



def main(): 
    fm_welcome() 
    while True:
        fm_menu() 
        choice = input("Select a conversion (a/b)")
        print()
        
        if choice == 'a': 
            feet = float(input("Enter Feet: "))
            meters = c.to_meters(feet)
            print(round(meters, 2), "meters")

        elif choice == 'b':
            #this is for step 14
            meters = float(input("Enter Meters: "))
            feet = c.to_feet(meters)
            print(round(feet, 2), "feet")

        else:
            print("You did not enter a valid selection")

        more = input("Would you like to perform another conversion? (y/n)")
        print()

        if more != "y":
            print("Thanks, Bye!")
            break




if __name__ == "__main__": main()