#Name: Andrew Young
#Class: INFO 1200
#Section: See syllabus, schedule, or Canvas course for section number
#Professor: Bartholomew
#Date: 9/19/2024
#Project #: M03
#By submitting this assignment, I declare that the source code contained in this assignment was written s#olely by me, unless specifically provided in the assignment. I attest that no part of this assignment, i#n whole or in part, was generated by Generative Artificial Intelligence (e.g., ChatGPT, Gemini, Copilot, #Claude, etc.) nor obtained from a paid solution service (e.g., Chegg, Course Hero, Bartleby, etc.). I un#derstand that copying any source code, in whole or in part, constitutes cheating, and that I will receiv#e a zero on this project if I am found in violation of this policy.

print("Andrew Young's Pay Check Calculator App") #print name of app
print()# print blank space

Hours_Worked = float(input("Hours Worked: "))#create variable Hours worked

Pay_Rate = float(input("Hourly Pay Rate: "))#create variable pay rate

print ()#print blank space

Gross_Pay = Hours_Worked * Pay_Rate#calculate gross pay

print("Gross Pay: " + str(Gross_Pay))#print the gross pay of user

Tax_Rate = .18#tax rate

print("Tax Rate: " + str(Tax_Rate))#print taxe rate of user

Tax_Amount = Gross_Pay * (Tax_Rate)#calculate tax amount of user

print("Tax Amount: " + str(Tax_Amount))#print tax amount

Take_Home_Pay = round(Gross_Pay - Tax_Amount, 2)#calculate take home pay of user

print("Take Home Pay: " + str(Take_Home_Pay))#print the take home pay of user