#Name: Andrew Young
#Class: INFO 1200
#Section: See syllabus, schedule, or Canvas course for section number
#Professor: Bartholomew
#Date:9/19/24
#Project #: M03
#By submitting this assignment, I declare that the source code contained in this assignment was written s#olely by me, unless specifically provided in the assignment. I attest that no part of this assignment, i#n whole or in part, was generated by Generative Artificial Intelligence (e.g., ChatGPT, Gemini, Copilot, #Claude, etc.) nor obtained from a paid solution service (e.g., Chegg, Course Hero, Bartleby, etc.). I un#derstand that copying any source code, in whole or in part, constitutes cheating, and that I will receiv#e a zero on this project if I am found in violation of this policy.

print("Andrew Young Tip Calculator App")#print name of app

print()#print blank space

Cost_of_Meal = float(input("Cost of Meal: "))#user input cost of meal

Tip_Percentage = float(input("Tip Percent: "))#user input tip percentage

Tip_Amount = Cost_of_Meal * (Tip_Percentage / 100)#calculate tip amount

print()# print blank space

print("Tip Amount: " + str(Tip_Amount))#print tip amount

print("Total Meal Cost: " + str(round(Cost_of_Meal + Tip_Amount, 2)))#print total cost of meal