#Name: Andrew Young
#Class: INFO 1200
#Section: See syllabus, schedule, or Canvas course for section number
#Professor: Bartholomew
#Date:9/19/24
#Project #: M03
#By submitting this assignment, I declare that the source code contained in this assignment was written s#olely by me, unless specifically provided in the assignment. I attest that no part of this assignment, i#n whole or in part, was generated by Generative Artificial Intelligence (e.g., ChatGPT, Gemini, Copilot, #Claude, etc.) nor obtained from a paid solution service (e.g., Chegg, Course Hero, Bartleby, etc.). I un#derstand that copying any source code, in whole or in part, constitutes cheating, and that I will receiv#e a zero on this project if I am found in violation of this policy.

print("Andrew Young's Registration App")#Intro statement

print()#blank space

first_name = input("First Name: ") #input first name

last_name = input("Last Name: ")#input last name

birth_year = input("Birth Year: ")#input birth year

print ()#print blank space

print("Welcome" + " " + first_name + " " + last_name)#welcome message

print("Your registration is complete") #print registration is complete

print() #print blank space

temp_password = first_name + "*" + birth_year #create temporary password

print("Your temporary password is: " + temp_password) #print the temporary password